services:
  - type: cron
    name: bitget-top20-screener
    schedule: '*/5 * * * *'  # every 5 minutes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 7323205302:AAEkxPBzPTVcUJoXU2BtsLa2S__E6ygxuUQ
      - key: CHAT_ID
        value: "-4793050089"
